blog/urls.py
from django.urls import path
from blog import views

app_name = 'blog'

urlpatterns = [
    path('', views.index, name="index"),
    path('create/', views.form_article_view, name="form_article")
]

main/urls.py
from django.conf.urls import path
from main import views

urlpatterns = [
    path('', views.index, name="index"),
]

public_python/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import include, path
from main import views

urlpatterns = [
	path('', views.index, name="index"),
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
import re
from django.db import models

class Article(models.Model):
	title = models.CharField(max_length=264,unique=True)
	publication_date = models.DateField()
	text = models.TextField()
	
	def __str__(self):
		return self.title

main/models.py
from django.db import models

class Topic(models.Model):
	top_name = models.CharField(max_length=264,unique=True)

	def __str__(self):
		return self.top_name

class Webpage(models.Model):
	topic = models.ForeignKey(Topic,on_delete=models.CASCADE)
	name = models.CharField(max_length=264,unique=True)
	url = models.URLField(unique=True)

	def __str__(self):
		return self.name

class AccessRecord(models.Model):
	name = models.ForeignKey(Webpage,on_delete=models.CASCADE)
	date = models.DateField()

	def __str__(self):
		return str(self.date)

class User(models.Model):
	firstname = models.CharField(max_length=264,unique=True)
	lastname = models.CharField(max_length=264,unique=True)
	email = models.EmailField()

	def __str__(self):
		return self.firstname

blog/forms.py
from django import forms
from blog.models import Article

class FormArticle(forms.ModelForm):
	class Meta:
		model = Article
		fields = '__all__'

blog/views.py
from django.shortcuts import render
from blog.models import Article
from . import forms
from blog.forms import FormArticle

def index(request):
	articles_list = Article.objects.order_by('-publication_date')
	articles_dict = {'articles':articles_list}
	return render(request, 'blog/index.html',context=articles_dict)

def form_article_view(request):
	form = FormArticle(None)
	if request.method == 'POST':
		form = FormArticle(request.POST)
		if form.is_valid():
			form.save(commit=True)
			print("Form is VALID")
			return index(request)

		else:
			print("not walid")

	return render(request,'blog/create-post.html', {'form':form})

main/views.py
from django.shortcuts import render
from main.models import Topic,Webpage,AccessRecord,User

def index(request):
	webpages_list = AccessRecord.objects.order_by('date')
	users_list = User.objects.all()
	date_dict = {'access_records':webpages_list,'users':users_list}
	return render(request, 'main/index.html',context=date_dict)

templates/blog/create-post.html
<!DOCTYPE html>
{% extends "main/base.html" %}
{% block body_block %}
	<form method="POST">
	Form
	{{ form.as_p }}
	{% csrf_token %}
	<input type="submit" value="Submit">
	</form>
{% endblock %}

templates/blog/index.html
<!DOCTYPE html>
{% extends "main/base.html" %}
{% block body_block %}

		<button><a href="{% url 'blog:form_article' %}">Add New Article</a></button>

		<button><a href="{% url 'admin:index' %}">Control Panel</a></button>

		<button><a href="{% url 'index' %}">Home</a></button>
		<div class="articles-container">
			{% if articles %}
				{% for art in articles %}
				<p>ARTICLE LENGTH: </p><span>{{ art.text.getTeaser }}</span>
				<article>
					<header>
						<div class="title">
							<h2>{{ art.title }}</h2>
							<p>{{ art.publication_date }}</p>
						</div>
					</header>
					
					<p>
						{{ art.text }}
					</p>
				</article>
				{% endfor %}
			{% else %}
			<p>No articles!</p>
			{% endif %}
		</div>
{% endblock %}

templates/main/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>Mateusz Wiśniewicz</title>
	
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
	<link rel="stylesheet" href="https://cdn.rawgit.com/konpa/devicon/df6431e323547add1b4cf45992913f15286456d3/devicon.min.css">
	<link rel="stylesheet" href="{% static './css/main.css' %}">

</head>

<body>
<header>
		<div class="container">
		<nav>
			<div class="hamburger-menu">
		  		<div class="bar"></div>	
			</div>
			<div class="logo">
				<a href="{% url 'index' %}"><span>M</span>Wisniewicz</a>
			</div>
			<ul class="nav-top">
				<li><a href="/">.home</a></li>
				<li><a href="/blog">.blog</a></li>
				<li><a href="#">.contact</a></li>
			</ul>
			
		</nav>
		</div>
	</header>

	{% block body_block %}

	{% endblock %}

	<main>
		<h1><span><i class="fa fa-cogs" aria-hidden="true"></i></span>Page under construction</h1><br>
		<h2>Visit my GitHub <span><i class="devicon-github-plain colored"></i></span>: <a href="https://github.com/mwisniewicz" target="__blank">mwisniewicz</a></h2>
	</main>

	<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
	<script>
		(function () {
	$('.hamburger-menu').on('click', function() {
		$('.bar').toggleClass('animate');
		$('.nav-top').toggleClass('displayIn');
	})
})();
	</script>
</body>
</html>

templates/main/index.html
<!DOCTYPE html>
{% extends "main/base.html" %}
{% block body_block %}
<h1>Welcome TO index</h1>
{% endblock %}

templates/main/index2.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>Homepage</title>
</head>
<body>
	<h2>WEB List</h2>
	<div class="django-class">
		{% if access_records %}
		<table>
			<thead>
				<th>Site Name</th>
				<th>Date</th>
			</thead>
		{% for acc in access_records %}
		<tr>
			<td>{{ acc.name }}</td>
			<td>{{ acc.date }}</td>
		</tr>
		{% endfor %}
		</table>
		{% else %}
		<p> No records! </p>
		
		{% endif %}
	</div>
	<h2>User List</h2>
	<div class="users-list">
		{% if users %}
			<table>
				<thead>
					<th>First Name</th>
					<th>Last Name</th>
					<th>E-mail</th>
				</thead>
				{% for usern in users %}
				<tr>
					<td>{{ usern.firstname }}</td>
					<td>{{ usern.lastname }}</td>
					<td>{{ usern.email }}</td>
				</tr>
				{% endfor %}
			</table>
			{% else %}
			<p>No Users</p>
		{% endif %}
	</div>
</body>
</html>